# This is a basic workflow to help you get started with Actions

name: Actions tests, write a file

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [issues]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_issues:
    name: Download issues from repo
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "number, title, labels, state, comments" > l-n-issues.csv
      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: l-n-issues.csv

